pub mod config;
pub mod engine;
pub mod git;
pub mod image;
pub mod paths;
pub mod state;

use anyhow::{Context, Result, bail};
use chrono::Utc;
use config::{Config, ResolvedRepository};
use engine::{ContainerSpec, DockerEngine, Engine};
use git::Git;
use image::ImageManager;
use paths::{JboxPaths, safe_target};
use state::{RepoState, Session, SessionState, StateStore};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{io, io::IsTerminal, io::Write};

pub const JCODE_SOCKET: &str = "/home/jbox/.local/share/jcode/jbox.sock";

const INIT_CONFIG: &str = r#"# Generated by `jbox init`. This primary repository is the workspace.
version = 1

[runtime]
backend = "kata"

[resources]
cpus = 8
memory = "16G"
disk = "40G" # Recorded for future VM disk sizing, not enforced by Docker/Kata yet.
ttl = "24h"

[image]
dockerfile = ".jbox/Dockerfile"

[workspace]
mount = "/workspace/project"

[network]
internet = true
host = false
lan = false

[jcode]
persistent_credentials = true
# These project defaults override the host Jcode client for jbox sessions.
# Remove an option to inherit that value from the host Jcode client instead.
default_provider = "openai"
default_model = "gpt-5.6-terra"
openai_reasoning_effort = "high"
openai_service_tier = "off"

[[jcode.skills]]
# `gh skill install` runs inside the guest after GitHub CLI authentication.
# Omit `skill` to install every discoverable skill in this repository.
repository = "bwbioinfo/skills"
# skill = "scanpy"
# pin = "v1.2.3"
# allow_hidden_dirs = true

[jcode.agent]
# Session-wide guidance is mounted as ~/AGENTS.md, not written to the worktree.
instructions = """
Use the `work-with-geonic` skill for all work in this workspace.
Use the `jbox` skill for workspace, lifecycle, isolation, or credential tasks.
Use the `jcode` skill for Jcode configuration, remote sessions, and authentication.
"""

[git]
network = true
# GitHub CLI credentials are required for the default private skills source.
# Jbox mounts only ~/.config/gh/hosts.yml, read-only, into the guest.
credentials = "github-cli"

[git.author]
# Read user.name and user.email from the host global Git config without
# mounting it into the guest. Set either key here to override that field.
inherit_host = true
# name = "Your Name"
# email = "you@example.com"
"#;

pub struct App {
    pub paths: JboxPaths,
    pub state: StateStore,
    git: Git,
    engine: DockerEngine,
}

/// Explicit opt-ins for accepting work that is not a simple clean,
/// fast-forward snapshot. Every mode is off by default so normal acceptance
/// remains non-destructive.
#[derive(Debug, Clone, Copy, Default)]
pub struct AcceptOptions {
    /// Commit visible generated-worktree changes before accepting them.
    pub checkpoint: bool,
    /// Temporarily stash dirty host files and reapply them after acceptance.
    pub stash_host: bool,
    /// Merge, rather than fast-forward, a guest snapshot into a diverged host branch.
    pub merge: bool,
}

/// Values that differ between a new guest and restarting a retained session.
/// Grouping them prevents the container construction interface from growing
/// as restart-specific behavior is added.
struct SessionLaunch {
    image: String,
    ssh_host: String,
    reuse_runtime_state: bool,
}

impl App {
    pub fn open() -> Result<Self> {
        let paths = JboxPaths::discover()?;
        paths.ensure()?;
        Ok(Self {
            state: StateStore::new(paths.clone()),
            paths,
            git: Git,
            engine: DockerEngine,
        })
    }

    pub fn doctor(&self) -> Result<()> {
        println!("jbox state: {}", self.paths.data.display());
        println!(
            "KVM: {}",
            if Path::new("/dev/kvm").exists() {
                "available"
            } else {
                "missing"
            }
        );
        println!(
            "VSOCK: {}",
            if Path::new("/dev/vhost-vsock").exists() {
                "available"
            } else {
                "missing: load vhost_vsock"
            }
        );
        let vhost_net = std::fs::read_to_string("/proc/modules")
            .map(|modules| modules.lines().any(|line| line.starts_with("vhost_net ")))
            .unwrap_or(false);
        println!(
            "Kata guest networking: {}",
            if vhost_net {
                "vhost_net loaded"
            } else {
                "vhost_net missing: run `sudo modprobe vhost_net`"
            }
        );
        match self.engine.check() {
            Ok(()) => println!("Docker + Kata runtime: ready"),
            Err(error) => {
                println!("Docker + Kata runtime: unavailable");
                println!("  {error:#}");
                println!(
                    "  Install Kata, register it as Docker's `kata` OCI runtime, then run `docker info`."
                );
            }
        }
        println!(
            "Network: Docker bridge grants Internet access but cannot enforce host/LAN denial by itself. Apply host firewall policy before treating this boundary as strict."
        );
        Ok(())
    }

    /// Create a project-local configuration and a Dockerfile that extends the
    /// jbox base image. Existing files are deliberately never replaced.
    pub fn init(&self, input: &Path, tools: &[String]) -> Result<()> {
        let project = Config::repository_root(input)?;
        let config = project.join(".jbox.toml");
        if config.exists() {
            bail!(
                "{} already exists; `jbox init` never overwrites configuration",
                config.display()
            );
        }
        for tool in tools {
            if !valid_apt_package(tool) {
                bail!(
                    "invalid --tool `{tool}`: use a simple Debian package name containing only lowercase letters, digits, `+`, `.`, or `-`"
                );
            }
        }

        let dockerfile = project.join(".jbox/Dockerfile");
        let created_dockerfile = !dockerfile.exists();
        if dockerfile.exists() && !dockerfile.is_file() {
            bail!("{} exists but is not a file", dockerfile.display());
        }
        if dockerfile.exists() && !tools.is_empty() {
            bail!(
                "{} already exists; add packages there rather than overwriting it",
                dockerfile.display()
            );
        }
        if created_dockerfile {
            std::fs::create_dir_all(
                dockerfile
                    .parent()
                    .context("template Dockerfile has no parent directory")?,
            )?;
            std::fs::write(&dockerfile, init_dockerfile(tools))?;
        }
        std::fs::write(&config, INIT_CONFIG)?;
        println!("created {}", config.display());
        if !created_dockerfile {
            println!("using existing {}", dockerfile.display());
        } else if tools.is_empty() {
            println!(
                "created {}. Add Debian packages with a RUN instruction, then jbox rebuilds the image when it changes.",
                dockerfile.display()
            );
        } else {
            println!(
                "created {} with: {}",
                dockerfile.display(),
                tools.join(", ")
            );
        }
        Ok(())
    }

    pub fn create(&self, input: &Path, no_attach: bool) -> Result<String> {
        let (config, primary) = Config::load(input)?;
        let git_author = config.git.author.resolve()?;
        if git_author.name.is_none() || git_author.email.is_none() {
            println!(
                "Guest Git author is incomplete. Set host `git config --global user.name` and `user.email`, or override [git.author] in .jbox.toml."
            );
        }
        let session_id = state::new_session_id();

        let mut resolved = vec![ResolvedRepository {
            source: primary.clone(),
            mount: config.workspace.mount.clone(),
            name: config.project_name(&primary),
        }];
        resolved.extend(config.resolve_repositories(&primary)?);
        config.validate_repositories(&resolved)?;
        self.engine.check()?;

        if config.git.network && config.git.credentials == "jbox" {
            self.paths.ensure_credentials()?;
        }
        let image = ImageManager::new(&self.paths).ensure(&config, &primary)?;
        let ssh_host = self.next_ssh_host(&session_id)?;
        let session_dir = self.paths.sessions.join(&session_id);
        let worktrees = session_dir.join("worktrees");
        std::fs::create_dir_all(&worktrees)?;

        let mut repos: Vec<RepoState> = Vec::with_capacity(resolved.len());
        for repo in &resolved {
            let worktree = worktrees.join(&repo.name);
            let created = match self
                .git
                .add_worktree(&repo.source, &worktree, &session_id, &repo.name)
                .with_context(|| format!("could not create worktree for {}", repo.source.display()))
            {
                Ok(created) => created,
                Err(error) => {
                    for created_repo in &repos {
                        let _ = self.git.remove_worktree(
                            &created_repo.source,
                            &created_repo.worktree,
                            false,
                        );
                    }
                    return Err(error);
                }
            };
            println!(
                "{}: sandbox branch {} starts at {}",
                repo.name, created.branch, created.commit
            );
            let host_gitfile = session_dir
                .join("host-gitfiles")
                .join(format!("{}.git", repo.name));
            if let Err(error) = self.git.isolate_guest_metadata(
                &repo.source,
                &worktree,
                &created.branch,
                &created.commit,
                &host_gitfile,
                &git_author,
            ) {
                let _ = self.git.remove_worktree(&repo.source, &worktree, false);
                self.cleanup_worktrees(&repos);
                let _ = std::fs::remove_dir_all(&session_dir);
                return Err(error).context("could not prepare isolated guest Git metadata");
            }
            // `isolate_guest_metadata` hard-resets the generated worktree to
            // its session base. Snapshot Beads *after* that reset so a current
            // host export, including uncommitted task updates, reaches the
            // guest rather than being silently reverted to HEAD.
            let beads_snapshot = match self.git.snapshot_beads_export(&repo.source, &worktree) {
                Ok(snapshot) => snapshot,
                Err(error) => {
                    let provisional = RepoState {
                        name: repo.name.clone(),
                        source: repo.source.clone(),
                        worktree: worktree.clone(),
                        mount: repo.mount.clone(),
                        branch: created.branch.clone(),
                        base_commit: created.commit.clone(),
                        host_gitfile: host_gitfile.clone(),
                        beads_snapshot: None,
                        beads_bootstrap: Vec::new(),
                    };
                    let _ = self.git.restore_guest_metadata(&provisional);
                    let _ = self.git.remove_worktree(&repo.source, &worktree, false);
                    self.cleanup_worktrees(&repos);
                    let _ = std::fs::remove_dir_all(&session_dir);
                    return Err(error).with_context(|| {
                        format!(
                            "could not snapshot Beads task context for {}",
                            repo.source.display()
                        )
                    });
                }
            };
            repos.push(RepoState {
                name: repo.name.clone(),
                source: repo.source.clone(),
                worktree,
                mount: repo.mount.clone(),
                branch: created.branch,
                base_commit: created.commit,
                host_gitfile,
                beads_snapshot,
                beads_bootstrap: Vec::new(),
            });
        }

        let ssh = self.paths.session_ssh_dir(&session_id);
        if let Err(error) = self.paths.create_session_ssh(&ssh) {
            self.cleanup_worktrees(&repos);
            let _ = std::fs::remove_dir_all(&session_dir);
            return Err(error).context("could not create session SSH credentials");
        }
        let ssh_agent_pid = match self.paths.start_session_ssh_agent(&ssh) {
            Ok(pid) => pid,
            Err(error) => {
                self.cleanup_worktrees(&repos);
                let _ = std::fs::remove_dir_all(&session_dir);
                return Err(error);
            }
        };
        let container_name = format!("jbox-{session_id}");
        let spec = match self.container_spec(
            &config,
            &repos,
            &container_name,
            &ssh,
            SessionLaunch {
                image: image.clone(),
                ssh_host: ssh_host.clone(),
                reuse_runtime_state: false,
            },
        ) {
            Ok(spec) => spec,
            Err(error) => {
                self.cleanup_worktrees(&repos);
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                let _ = std::fs::remove_dir_all(&session_dir);
                return Err(error);
            }
        };
        let port = match self.engine.start(&spec) {
            Ok(port) => port,
            Err(error) => {
                self.cleanup_worktrees(&repos);
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                let _ = std::fs::remove_dir_all(&session_dir);
                return Err(error);
            }
        };
        let known_hosts_tag = match self.paths.trust_session_host(&ssh_host, &session_id) {
            Ok(tag) => tag,
            Err(error) => {
                let _ = self.engine.stop(&container_name);
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                self.cleanup_worktrees(&repos);
                let _ = std::fs::remove_dir_all(&session_dir);
                return Err(error);
            }
        };
        // Capture the host-visible result of trusted bootstrap before a local
        // TUI can connect. Those files are jbox infrastructure, not agent
        // edits, and their exact digests remain the safety boundary.
        for repo in &mut repos {
            repo.beads_bootstrap = self.git.capture_beads_bootstrap(&repo.worktree);
        }

        let now = Utc::now();
        let session = Session {
            version: 1,
            id: session_id.clone(),
            state: SessionState::Running,
            container_name,
            ssh_host: ssh_host.clone(),
            ssh_port: port,
            ssh_agent_pid,
            known_hosts_tag,
            created_at: now,
            last_activity_at: now,
            ttl_seconds: config.resources.ttl_seconds,
            config_path: config.path,
            image,
            repos,
            jcode_default_provider: config.jcode.default_provider.clone(),
            jcode_default_model: config.jcode.default_model.clone(),
        };
        self.state.save(&session)?;
        println!("jbox session {session_id} is running on {ssh_host}:{port}");
        if !no_attach {
            self.attach(&session_id)?;
        }
        Ok(session_id)
    }

    fn container_spec(
        &self,
        config: &Config,
        repos: &[RepoState],
        name: &str,
        ssh: &Path,
        launch: SessionLaunch,
    ) -> Result<ContainerSpec> {
        let mut mounts = Vec::new();
        let mut environment = Vec::new();
        for repo in repos {
            mounts.push((repo.worktree.clone(), safe_target(&repo.mount)?, true));
        }
        // Each worktree contains a jbox-snapshotted `.beads/issues.jsonl` when
        // its source repository uses Beads. The guest imports that portable
        // task context into its own writable Beads database before Jcode
        // starts, never exposing the host database or its locks/secrets.
        let beads_workspaces = repos
            .iter()
            .filter(|repo| repo.worktree.join(".beads/issues.jsonl").is_file())
            .collect::<Vec<_>>();
        if !beads_workspaces.is_empty() {
            environment.push((
                "JBOX_BEADS_WORKSPACE_COUNT".into(),
                beads_workspaces.len().to_string(),
            ));
            for (index, repo) in beads_workspaces.into_iter().enumerate() {
                environment.push((
                    format!("JBOX_BEADS_WORKSPACE_{index}"),
                    safe_target(&repo.mount)?.to_string_lossy().into_owned(),
                ));
                environment.push((format!("JBOX_BEADS_PREFIX_{index}"), repo.name.clone()));
            }
        }
        for mount in &config.mounts {
            mounts.push((
                mount
                    .source_path
                    .clone()
                    .context("configured mount source was not resolved")?,
                safe_target(&mount.target)?,
                mount.writable,
            ));
        }
        if config.jcode.persistent_credentials {
            for (source, target) in self.paths.jcode_credential_mounts()? {
                mounts.push((source, target, true));
            }
        }
        if config.jcode.default_provider.is_some()
            || config.jcode.default_model.is_some()
            || config.jcode.openai_reasoning_effort.is_some()
            || config.jcode.openai_service_tier.is_some()
        {
            let jcode_config = ssh
                .parent()
                .context("session SSH directory lacks a parent")?
                .join("runtime/jcode-config.toml");
            std::fs::create_dir_all(
                jcode_config
                    .parent()
                    .context("session Jcode configuration has no parent")?,
            )?;
            std::fs::write(&jcode_config, guest_jcode_config(&config.jcode))?;
            std::fs::set_permissions(&jcode_config, std::fs::Permissions::from_mode(0o600))?;
            // This nested, session-owned file mount intentionally overrides
            // only config.toml inside the dedicated credential-home mount.
            // Auth files remain in jbox-owned persistent credential state.
            mounts.push((
                jcode_config,
                PathBuf::from("/home/jbox/.jcode/config.toml"),
                true,
            ));
        }
        // This is deliberately session-scoped rather than credential-scoped.
        // Mounting a jcode external-provider directory beneath ~/.local/share
        // can cause Docker to create its parent directories as root, so the
        // unprivileged guest cannot create the daemon socket without this
        // explicit, jbox-owned runtime mount.
        let runtime = ssh
            .parent()
            .context("session SSH directory lacks a parent")?
            .join("runtime/jcode");
        std::fs::create_dir_all(&runtime)?;
        std::fs::set_permissions(&runtime, std::fs::Permissions::from_mode(0o700))?;
        mounts.push((
            runtime,
            PathBuf::from("/home/jbox/.local/share/jcode"),
            true,
        ));
        if let Some(instructions) = config.jcode.agent.instructions.as_deref() {
            let agent_instructions = ssh
                .parent()
                .context("session SSH directory lacks a parent")?
                .join("runtime/AGENTS.md");
            std::fs::write(
                &agent_instructions,
                format!("# Jbox session instructions\n\n{instructions}\n"),
            )?;
            std::fs::set_permissions(&agent_instructions, std::fs::Permissions::from_mode(0o600))?;
            // Jcode loads ~/AGENTS.md after the project AGENTS.md. Mounting a
            // session file here preserves the generated worktree unchanged.
            mounts.push((
                agent_instructions,
                PathBuf::from("/home/jbox/AGENTS.md"),
                false,
            ));
        }
        if !config.jcode.skills.is_empty() {
            let skills_dir = ssh
                .parent()
                .context("session SSH directory lacks a parent")?
                .join("runtime/skills");
            std::fs::create_dir_all(&skills_dir)?;
            std::fs::set_permissions(&skills_dir, std::fs::Permissions::from_mode(0o700))?;
            mounts.push((skills_dir, PathBuf::from("/home/jbox/.agents/skills"), true));
            environment.push((
                "JBOX_SKILL_COUNT".into(),
                if launch.reuse_runtime_state {
                    // A session reaches Stopped only after its guest ran
                    // successfully. Its session-owned skills directory is
                    // therefore complete and can be reused without another
                    // network-bound `gh skill install` before SSH starts.
                    "0".into()
                } else {
                    config.jcode.skills.len().to_string()
                },
            ));
            if !launch.reuse_runtime_state {
                for (index, source) in config.jcode.skills.iter().enumerate() {
                    environment.push((
                        format!("JBOX_SKILL_{index}_REPOSITORY"),
                        source.repository.clone(),
                    ));
                    environment.push((
                        format!("JBOX_SKILL_{index}_NAME"),
                        source.skill.clone().unwrap_or_default(),
                    ));
                    environment.push((
                        format!("JBOX_SKILL_{index}_PIN"),
                        source.pin.clone().unwrap_or_default(),
                    ));
                    environment.push((
                        format!("JBOX_SKILL_{index}_ALLOW_HIDDEN"),
                        if source.allow_hidden_dirs { "1" } else { "0" }.into(),
                    ));
                }
            }
        }
        if config.git.network && config.git.credentials == "jbox" {
            mounts.push((
                self.paths.credentials.join("git").join("id_ed25519"),
                PathBuf::from("/home/jbox/.ssh/id_ed25519"),
                false,
            ));
        }
        if config.git.credentials == "github-cli" {
            mounts.push((
                self.paths.github_cli_hosts()?,
                PathBuf::from("/home/jbox/.config/gh/hosts.yml"),
                false,
            ));
            environment.push(("JBOX_GITHUB_CLI_CREDENTIALS".into(), "1".into()));
        }
        mounts.push((
            ssh.join("authorized_keys"),
            PathBuf::from("/home/jbox/.ssh/authorized_keys"),
            false,
        ));
        Ok(ContainerSpec {
            name: name.into(),
            image: launch.image,
            mounts,
            cpus: config.resources.cpus,
            memory: config.resources.memory.clone(),
            network: config.network.clone(),
            ssh_host: launch.ssh_host,
            environment,
        })
    }

    pub fn attach(&self, id: &str) -> Result<()> {
        let mut session = self.load_session(id)?;
        let mount = session.repos[0].mount.clone();
        self.attach_session(&mut session, &mount)
    }

    /// Attach from a repository starts Jcode in the matching selected mount,
    /// rather than always opening the primary repository of a multi-repo VM.
    pub fn attach_from_repository(&self, input: &Path) -> Result<()> {
        let Some((mut session, repo)) =
            self.select_repository_worktree(input, "attach", Some(SessionState::Running))?
        else {
            return Ok(());
        };
        self.attach_session(&mut session, &repo.mount)
    }

    fn attach_session(&self, session: &mut Session, mount: &str) -> Result<()> {
        self.require_running(session)?;
        self.touch(session)?;
        render_jbox_session_chrome(&session.id, mount)?;
        let ssh_socket = self.paths.session_ssh_dir(&session.id).join("agent.sock");
        let args = jcode_attach_args(&session.ssh_host, mount);
        let status = Command::new("jcode")
            .args(args)
            .env("SSH_AUTH_SOCK", ssh_socket)
            .status()
            .context("could not launch local jcode")?;
        if !status.success() {
            bail!("local jcode exited with {status}");
        }
        Ok(())
    }

    pub fn shell(&self, id: &str) -> Result<()> {
        let mut session = self.load_session(id)?;
        let mount = session.repos[0].mount.clone();
        self.shell_session(&mut session, &mount)
    }

    /// Open a login shell rooted at the repository selected from the host.
    pub fn shell_from_repository(&self, input: &Path) -> Result<()> {
        let Some((mut session, repo)) =
            self.select_repository_worktree(input, "open a shell in", Some(SessionState::Running))?
        else {
            return Ok(());
        };
        self.shell_session(&mut session, &repo.mount)
    }

    fn shell_session(&self, session: &mut Session, mount: &str) -> Result<()> {
        self.require_running(session)?;
        self.touch(session)?;
        render_jbox_session_chrome(&session.id, mount)?;
        let config = self.paths.write_ssh_config(session)?;
        let command = format!("cd {mount} && exec bash -l");
        let status = Command::new("ssh")
            .args(["-F", config.to_str().unwrap(), "jbox", "-t", &command])
            .status()?;
        if !status.success() {
            bail!("ssh exited with {status}");
        }
        Ok(())
    }

    pub fn import_credentials(&self, all: bool, confirmed: bool, replace: bool) -> Result<()> {
        if !all {
            bail!(
                "credential import requires `--all`; jbox never guesses which provider credentials to copy"
            );
        }
        let candidates = self.paths.local_credentials()?;
        if candidates.is_empty() {
            println!("No supported local Jcode credential stores were found.");
            return Ok(());
        }
        println!("The following provider credential stores may be copied into jbox-managed state:");
        for credential in &candidates {
            println!(
                "- {} ({})",
                credential.provider_hint,
                credential.source.display()
            );
        }
        if !confirmed {
            println!(
                "Nothing was copied. Re-run with `jbox credentials import --all --yes` to explicitly copy these credentials. This never mounts your host credential directories."
            );
            return Ok(());
        }
        let report = self.paths.import_local_credentials(replace)?;
        for credential in &report.imported {
            println!("imported {}", credential.provider_hint);
        }
        for credential in &report.retained {
            println!(
                "retained existing jbox credential for {}; use --replace to overwrite it",
                credential.provider_hint
            );
        }
        println!(
            "Credentials are stored only under {} and are available to newly created jbox guests.",
            self.paths.credentials.join("jcode").display()
        );
        Ok(())
    }

    pub fn stop(&self, id: &str) -> Result<()> {
        let mut session = self.load_session(id)?;
        if session.state == SessionState::Running {
            self.engine.stop(&session.container_name)?;
            self.paths.stop_session_ssh_agent(session.ssh_agent_pid);
            self.paths.untrust_session_host(&session.known_hosts_tag)?;
            for repo in &session.repos {
                self.git.restore_and_import_guest_metadata(repo)?;
            }
            session.state = SessionState::Stopped;
            self.state.save(&session)?;
        }
        println!("jbox session {id} stopped. Worktrees were retained.");
        Ok(())
    }

    /// Stop the selected machine. Stopping is session-wide, so confirmation
    /// explicitly calls out that sibling repositories will also disconnect.
    pub fn stop_from_repository(&self, input: &Path) -> Result<()> {
        let Some((session, _)) = self.select_repository_worktree(input, "stop", None)? else {
            return Ok(());
        };
        print!(
            "Stop session {} and disconnect all {} repository workspaces? [y/N]: ",
            session.id,
            session.repos.len()
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("stop cancelled.");
            return Ok(());
        }
        self.stop(&session.id)
    }

    /// Accept the latest committed snapshot from every repository in a session
    /// into the explicitly selected host branch. Unlike `stop`, this keeps a
    /// running guest and its isolated Git metadata intact for further work.
    pub fn accept(&self, id: &str, target: &str, options: AcceptOptions) -> Result<()> {
        let mut session = self.load_session(id)?;
        let targets = vec![target.to_owned(); session.repos.len()];
        let repos = session.repos.clone();
        self.accept_snapshots(&mut session, &repos, &targets, options)
    }

    /// Interactively select a session from the current repository, then
    /// accept every repository in that development machine. With no explicit
    /// branch each host repository uses its own checked-out branch, which
    /// supports sessions spanning repositories with different default names.
    pub fn accept_all_from_repository(
        &self,
        input: &Path,
        target: Option<&str>,
        options: AcceptOptions,
    ) -> Result<()> {
        let Some((mut session, _)) =
            self.select_repository_worktree(input, "accept all worktrees from", None)?
        else {
            return Ok(());
        };
        let targets = session
            .repos
            .iter()
            .map(|repo| match target {
                Some(target) => Ok(target.to_owned()),
                None => {
                    let branch = self.git.current_branch(&repo.source)?;
                    if branch.is_empty() {
                        bail!(
                            "cannot accept all: host repository {} is detached; check out a branch or pass --into <branch>",
                            repo.source.display()
                        );
                    }
                    Ok(branch)
                }
            })
            .collect::<Result<Vec<_>>>()?;

        println!(
            "Accept every repository from session {} into these host branches:",
            session.id
        );
        for (repo, target) in session.repos.iter().zip(&targets) {
            println!("  {}: {} -> {target}", repo.name, repo.branch);
        }
        let action = if options.merge {
            "Merge"
        } else {
            "Fast-forward"
        };
        print!(
            "{action} all {} worktrees from session {}? [y/N]: ",
            session.repos.len(),
            session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("accept all cancelled.");
            return Ok(());
        }
        let repos = session.repos.clone();
        self.accept_snapshots(&mut session, &repos, &targets, options)
    }

    /// Interactively accept exactly the repository selected by the current
    /// directory. This avoids surprising cross-repository acceptance when a
    /// multi-repository session is selected from one checkout.
    pub fn accept_from_repository(
        &self,
        input: &Path,
        target: Option<&str>,
        options: AcceptOptions,
    ) -> Result<()> {
        let repository = Config::repository_root(input)?;
        let target = match target {
            Some(target) => target.to_owned(),
            None => self.git.current_branch(&repository)?,
        };
        if target.is_empty() {
            bail!(
                "{} is detached; check out the branch to accept into or pass --into <branch>",
                repository.display()
            );
        }
        let action = if options.merge {
            "merge"
        } else {
            "fast-forward"
        };
        let selection_action = format!("{action} `{target}` from");
        let Some((mut session, repo)) =
            self.select_repository_worktree(input, &selection_action, None)?
        else {
            return Ok(());
        };
        let Some(options) = self.prompt_merge_if_diverged(&session, &repo, &target, options)?
        else {
            return Ok(());
        };
        let action = if options.merge {
            "Merge"
        } else {
            "Fast-forward"
        };
        print!(
            "{action} `{target}` to {} from session {}? [y/N]: ",
            repo.branch, session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("accept cancelled.");
            return Ok(());
        }
        self.accept_snapshots(
            &mut session,
            std::slice::from_ref(&repo),
            &[target],
            options,
        )
    }

    /// Repository-scoped acceptance is interactive already. If its clean host
    /// branch cannot fast-forward, offer the explicit merge right there rather
    /// than making the user repeat the selection with `--merge`.
    fn prompt_merge_if_diverged(
        &self,
        session: &Session,
        repo: &RepoState,
        target: &str,
        mut options: AcceptOptions,
    ) -> Result<Option<AcceptOptions>> {
        if options.merge {
            return Ok(Some(options));
        }
        // Import first so the ancestry question covers every guest commit
        // created since the prior accept, while leaving the host branch alone.
        self.git.import_guest_commits(repo)?;
        self.git.preflight_accept_target(repo, target)?;
        if (!options.stash_host && !self.git.host_is_clean(repo)?)
            || self.git.snapshot_can_fast_forward(repo, target)?
        {
            return Ok(Some(options));
        }
        println!(
            "Fast-forward cannot accept `{target}` because it has diverged from session branch `{}`.",
            repo.branch
        );
        println!(
            "A merge creates a host merge commit. If Git reports conflicts, the jbox session remains available and `jbox accept --continue` or `jbox accept --abort` completes recovery."
        );
        print!(
            "Create a merge from {} for session {} now? [y/N]: ",
            repo.branch, session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("accept cancelled. No host branch was changed.");
            return Ok(None);
        }
        options.merge = true;
        Ok(Some(options))
    }

    /// Complete a host merge created by an earlier `jbox accept --merge`.
    /// The selected jbox session is retained throughout. Git itself remains
    /// responsible for the user's conflict resolution content.
    pub fn continue_accept_from_repository(&self, input: &Path) -> Result<()> {
        let Some((mut session, repo)) =
            self.select_paused_acceptance_worktree(input, "continue")?
        else {
            return Ok(());
        };
        let Some(conflicts) = self.git.host_merge_conflicts(&repo)? else {
            bail!(
                "no acceptance merge is paused in {}; choose the worktree whose host checkout is merging",
                repo.source.display()
            );
        };
        if !conflicts.is_empty() {
            println!(
                "Acceptance is paused for session {}. Host merge conflicts in {}:\n{}",
                session.id,
                repo.source.display(),
                conflicts
            );
            bail!(
                "resolve and stage those files, then rerun `jbox accept --continue`; use `jbox accept --abort` to abandon the host merge"
            );
        }
        print!(
            "Commit the staged host merge for session {} and keep its jbox worktree? [y/N]: ",
            session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("continue acceptance cancelled. The host merge remains paused.");
            return Ok(());
        }
        self.git.continue_host_merge(&repo)?;
        println!(
            "completed acceptance merge for {}. Jbox session {} remains retained.",
            repo.name, session.id
        );
        self.touch(&mut session)
    }

    /// Abort only the pending host-side merge created by `accept --merge`.
    /// The generated worktree and its session branch remain available for a
    /// later rebase, merge, or inspection.
    pub fn abort_accept_from_repository(&self, input: &Path) -> Result<()> {
        let Some((mut session, repo)) = self.select_paused_acceptance_worktree(input, "abort")?
        else {
            return Ok(());
        };
        let Some(conflicts) = self.git.host_merge_conflicts(&repo)? else {
            bail!(
                "no acceptance merge is paused in {}; choose the worktree whose host checkout is merging",
                repo.source.display()
            );
        };
        println!(
            "Abort the host merge for session {} in {}. The jbox session branch {} stays retained.{}",
            session.id,
            repo.source.display(),
            repo.branch,
            if conflicts.is_empty() {
                ""
            } else {
                " Unresolved files are present."
            }
        );
        print!("Abort this host merge? [y/N]: ");
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("abort acceptance cancelled. The host merge remains paused.");
            return Ok(());
        }
        self.git.abort_host_merge(&repo)?;
        println!(
            "aborted host merge for {}. Jbox session {} and branch {} remain retained.",
            repo.name, session.id, repo.branch
        );
        self.touch(&mut session)
    }

    fn accept_snapshots(
        &self,
        session: &mut Session,
        repos: &[RepoState],
        targets: &[String],
        options: AcceptOptions,
    ) -> Result<()> {
        if repos.len() != targets.len() {
            bail!("internal error: every accepted repository needs an acceptance target");
        }

        // Detect every unresolved conflict before making a checkpoint commit in
        // any sibling worktree. This prevents a multi-repository command from
        // producing a partial set of surprise commits.
        if options.checkpoint {
            for repo in repos {
                self.git.validate_session_checkpoint(repo)?;
            }
            for repo in repos {
                if self.git.checkpoint_session_changes(repo, &session.id)? {
                    println!("checkpointed generated worktree changes for {}", repo.name);
                }
            }
        }
        // Import every guest branch, and preflight every host checkout, before
        // moving any host ref. A divergent sibling therefore leaves every host
        // repository untouched.
        for repo in repos {
            self.git.import_guest_commits(repo)?;
        }

        // Validate checked-out target branches before temporarily moving host
        // files into a stash. The actual clean-check runs after the stash.
        if options.stash_host {
            for (repo, target) in repos.iter().zip(targets) {
                self.git.preflight_accept_target(repo, target)?;
            }
        }

        let mut stashes = Vec::new();
        if options.stash_host {
            for repo in repos {
                if let Some(stash) = self.git.stash_host_changes(repo, &session.id)? {
                    println!(
                        "preserved uncommitted host changes for {} in a temporary stash",
                        repo.name
                    );
                    stashes.push((repo, stash));
                }
            }
        }

        let accept_result = (|| -> Result<()> {
            for (repo, target) in repos.iter().zip(targets) {
                if options.merge {
                    self.git.preflight_merge_snapshot(repo, target)?;
                } else {
                    self.git.preflight_accept_snapshot(repo, target)?;
                }
            }
            for (repo, target) in repos.iter().zip(targets) {
                if options.merge {
                    self.git.merge_snapshot(repo, target)?;
                } else {
                    self.git.fast_forward_snapshot(repo, target)?;
                }
                let verb = if options.merge { "merged" } else { "accepted" };
                println!(
                    "{verb} {} snapshot from {} into {}",
                    repo.name, repo.branch, target
                );
            }
            Ok(())
        })();

        if let Err(error) = accept_result {
            if !stashes.is_empty() {
                eprintln!(
                    "host changes remain safely stashed because acceptance did not finish; inspect `git stash list` in each affected host repository before retrying"
                );
            }
            return Err(error);
        }

        for (repo, stash) in stashes {
            self.git.restore_host_stash(repo, &stash)?;
            println!("restored preserved host changes for {}", repo.name);
        }

        self.touch(session)?;
        if session.state == SessionState::Running {
            println!(
                "jbox session {} remains running for further work.",
                session.id
            );
        }
        Ok(())
    }

    /// Rebase a single selected session worktree from its host repository. A
    /// live guest is explicitly stopped first so its isolated Git metadata is
    /// imported and restored before the host-side rebase changes the branch.
    pub fn rebase_from_repository(&self, input: &Path, onto: Option<&str>) -> Result<()> {
        let repository = Config::repository_root(input)?;
        let onto = match onto {
            Some(branch) => branch.to_owned(),
            None => self.git.current_branch(&repository)?,
        };
        if onto.is_empty() {
            bail!("{} is detached; pass --onto <branch>", repository.display());
        }
        let selection_action = format!("rebase onto `{onto}`");
        let Some((session, repo)) =
            self.select_repository_worktree(input, &selection_action, None)?
        else {
            return Ok(());
        };
        print!(
            "Rebase {} from session {} onto `{onto}`? [y/N]: ",
            repo.branch, session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("rebase cancelled.");
            return Ok(());
        }
        if session.state == SessionState::Running {
            println!(
                "stopping {} to safely synchronize its Git metadata...",
                session.id
            );
            self.stop(&session.id)?;
        }
        self.git.rebase_worktree(&repo, &onto)?;
        println!(
            "rebased {} onto `{onto}`. Run `jbox accept` to fast-forward it.",
            repo.branch
        );
        Ok(())
    }

    /// Open a host-local shell in the matching retained worktree. This is an
    /// intentional escape hatch for resolving a paused rebase or merge before
    /// a guest can safely be resumed. It never starts a container or changes
    /// the worktree itself.
    pub fn resolve(&self, id: &str, input: &Path) -> Result<()> {
        let session = self.load_session(id)?;
        let repository = Config::repository_root(input)?;
        let repo = session
            .repos
            .iter()
            .find(|repo| repo.source == repository)
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "session {id} has no worktree for {}; run `jbox resolve` from a participating repository",
                    repository.display()
                )
            })?;
        self.resolve_worktree(&session, repo)
    }

    pub fn resolve_from_repository(&self, input: &Path) -> Result<()> {
        let Some((session, repo)) = self.select_repository_worktree(input, "resolve", None)? else {
            return Ok(());
        };
        self.resolve_worktree(&session, &repo)
    }

    fn resolve_worktree(&self, session: &Session, repo: &RepoState) -> Result<()> {
        if !io::stdin().is_terminal() || !io::stdout().is_terminal() {
            bail!("`jbox resolve` needs an interactive terminal");
        }
        println!(
            "Opening a local host shell in retained worktree {} for session {}.",
            repo.worktree.display(),
            session.id
        );
        println!(
            "No guest is started and jbox changes no files. Resolve the Git operation, run `git rebase --continue` or `git merge --continue`, then exit and run `jbox resume`."
        );
        let status = Command::new("bash")
            .args(["--noprofile", "--norc"])
            .current_dir(&repo.worktree)
            .env("JBOX_RETAINED_SESSION", &session.id)
            .env("JBOX_RETAINED_WORKTREE", &repo.worktree)
            .status()
            .context("could not open a local shell in the retained worktree")?;
        if !status.success() {
            bail!("retained worktree shell exited with {status}");
        }
        Ok(())
    }

    /// Interactively inspect one worktree belonging to the repository beneath
    /// the current directory. This keeps multi-repository sessions focused on
    /// the repository the user is presently working in.
    pub fn status_from_repository(&self, input: &Path, diff: bool) -> Result<()> {
        let action = if diff { "diff" } else { "inspect" };
        let Some((session, repo)) = self.select_repository_worktree(input, action, None)? else {
            return Ok(());
        };
        self.status_repository_worktree(&session, &repo, diff)
    }

    /// Resume a stopped session from its retained worktrees. The worktree
    /// branch and image are reused. A fresh session SSH key and runtime state
    /// are created. A visible dirty worktree gets an explicit checkpoint offer
    /// before recreating its isolated guest Git metadata.
    pub fn resume(&self, id: &str) -> Result<()> {
        let mut session = self.load_session(id)?;
        if session.state == SessionState::Running {
            bail!("session {id} is already running; use `jbox attach {id}`");
        }
        if self.engine.is_running(&session.container_name)? {
            bail!(
                "runtime container for {id} is unexpectedly still running; use `jbox attach {id}` or `jbox stop {id}` first"
            );
        }
        let (config, primary) = Config::load(&session.config_path)?;
        self.validate_resume_config(&session, &config, &primary)?;
        self.engine.check()?;
        if config.git.network && config.git.credentials == "jbox" {
            self.paths.ensure_credentials()?;
        }
        let author = config.git.author.resolve()?;
        self.checkpoint_dirty_worktrees_before_resume(&session)?;
        for repo in &session.repos {
            if let Err(error) = self
                .git
                .prepare_retained_worktree_for_guest(repo, &author)
                .with_context(|| format!("could not prepare retained worktree {}", repo.name))
            {
                self.restore_retained_metadata(&session.repos);
                return Err(error);
            }
        }

        let ssh = self.paths.session_ssh_dir(&session.id);
        self.clear_stale_runtime_sockets(&ssh)?;
        let _ = std::fs::remove_dir_all(&ssh);
        if let Err(error) = self.paths.create_session_ssh(&ssh) {
            self.restore_retained_metadata(&session.repos);
            return Err(error).context("could not create resumed session SSH credentials");
        }
        let ssh_agent_pid = match self.paths.start_session_ssh_agent(&ssh) {
            Ok(pid) => pid,
            Err(error) => {
                self.restore_retained_metadata(&session.repos);
                return Err(error);
            }
        };
        let spec = match self.container_spec(
            &config,
            &session.repos,
            &session.container_name,
            &ssh,
            SessionLaunch {
                image: session.image.clone(),
                ssh_host: session.ssh_host.clone(),
                reuse_runtime_state: true,
            },
        ) {
            Ok(spec) => spec,
            Err(error) => {
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                self.restore_retained_metadata(&session.repos);
                return Err(error);
            }
        };
        let port = match self.engine.start(&spec) {
            Ok(port) => port,
            Err(error) => {
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                self.restore_retained_metadata(&session.repos);
                return Err(error);
            }
        };
        let known_hosts_tag = match self
            .paths
            .trust_session_host(&session.ssh_host, &session.id)
        {
            Ok(tag) => tag,
            Err(error) => {
                let _ = self.engine.stop(&session.container_name);
                self.paths.stop_session_ssh_agent(ssh_agent_pid);
                self.restore_retained_metadata(&session.repos);
                return Err(error);
            }
        };
        session.state = SessionState::Running;
        session.ssh_port = port;
        session.ssh_agent_pid = ssh_agent_pid;
        session.known_hosts_tag = known_hosts_tag;
        self.touch(&mut session)?;
        println!(
            "jbox session {} resumed on {}:{}",
            session.id, session.ssh_host, session.ssh_port
        );
        println!("Use `jbox attach {}` to reconnect.", session.id);
        Ok(())
    }

    /// Recreating isolated guest Git metadata includes a hard reset. Never do
    /// that over agent files. Ordinary changes can instead be checkpointed on
    /// the retained session branches with an explicit confirmation. Validate
    /// every candidate first, so an unresolved sibling operation cannot leave
    /// a partial set of new commits.
    fn checkpoint_dirty_worktrees_before_resume(&self, session: &Session) -> Result<()> {
        let mut changed = Vec::new();
        for repo in &session.repos {
            if self.git.validate_session_checkpoint(repo)? {
                changed.push(repo);
            }
        }
        if changed.is_empty() {
            return Ok(());
        }
        if !io::stdin().is_terminal() || !io::stdout().is_terminal() {
            bail!(
                "cannot resume {}: {} retained worktree(s) have uncommitted changes; run `jbox resume {}` in an interactive terminal to checkpoint them, or commit/stash them manually",
                session.id,
                changed.len(),
                session.id
            );
        }
        println!(
            "Session {} has uncommitted changes in retained worktrees:",
            session.id
        );
        for repo in &changed {
            println!("  - {} ({})", repo.name, repo.worktree.display());
        }
        println!(
            "Resuming recreates guest Git metadata. Jbox can preserve these files by committing them only to their session branch."
        );
        print!(
            "Checkpoint these changes, then resume session {}? [y/N]: ",
            session.id
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            bail!(
                "resume cancelled. No worktree files or branches were changed; commit or stash the retained changes before retrying"
            );
        }
        for repo in changed {
            if self
                .git
                .checkpoint_session_changes_for_resume(repo, &session.id)?
            {
                println!("checkpointed retained changes for {}", repo.name);
            }
        }
        Ok(())
    }

    /// Select a stopped retained session that contains the current repository.
    pub fn resume_from_repository(&self, input: &Path) -> Result<()> {
        let Some((session, _)) =
            self.select_repository_worktree(input, "resume", Some(SessionState::Stopped))?
        else {
            return Ok(());
        };
        print!("Resume session {}? [y/N]: ", session.id);
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("resume cancelled.");
            return Ok(());
        }
        self.resume(&session.id)
    }

    fn sessions_for_repository(&self, repository: &Path) -> Result<Vec<(Session, RepoState)>> {
        Ok(self
            .list_sessions()?
            .into_iter()
            .flat_map(|session| {
                let repositories = session
                    .repos
                    .iter()
                    .filter(|repo| repo.source == repository)
                    .cloned()
                    .collect::<Vec<_>>();
                repositories
                    .into_iter()
                    .map(move |repo| (session.clone(), repo))
            })
            .collect())
    }

    pub fn list(&self) -> Result<()> {
        let sessions = self.list_sessions()?;
        if sessions.is_empty() {
            println!("No jbox sessions.");
            return Ok(());
        }
        println!("ID\tSTATE\tLAST ACTIVITY\tREPOSITORIES");
        for s in sessions {
            println!(
                "{}\t{:?}\t{}\t{}",
                s.id,
                s.state,
                s.last_activity_at.format("%Y-%m-%d %H:%M UTC"),
                s.repos
                    .iter()
                    .map(|r| r.name.as_str())
                    .collect::<Vec<_>>()
                    .join(",")
            );
        }
        Ok(())
    }

    pub fn status(&self, id: &str, diff: bool) -> Result<()> {
        let session = self.load_session(id)?;
        println!("{} ({:?})", session.id, session.state);
        for repo in &session.repos {
            self.status_repository_worktree(&session, repo, diff)?;
        }
        Ok(())
    }

    pub fn clean(&self, id: Option<&str>, force: bool) -> Result<()> {
        let targets = match id {
            Some(id) => vec![self.load_session(id)?],
            None => self.list_sessions()?,
        };
        for mut session in targets {
            let changed = session.repos.iter().any(|r| {
                self.git
                    .has_uncommitted_or_unmerged_changes(r)
                    .unwrap_or(true)
            });
            if changed && !force {
                println!(
                    "refusing to clean {}: worktrees contain changes or commits. Use `jbox clean {} --force` only after inspecting `jbox status {}`.",
                    session.id, session.id, session.id
                );
                continue;
            }
            if session.state == SessionState::Running {
                self.engine.stop(&session.container_name)?;
                self.paths.stop_session_ssh_agent(session.ssh_agent_pid);
                self.paths.untrust_session_host(&session.known_hosts_tag)?;
                for repo in &session.repos {
                    self.git.restore_and_import_guest_metadata(repo)?;
                }
                session.state = SessionState::Stopped;
            }
            for repo in &session.repos {
                self.git
                    .remove_worktree(&repo.source, &repo.worktree, force)?;
            }
            self.state.remove(&session.id)?;
            let _ = std::fs::remove_dir_all(self.paths.sessions.join(&session.id));
            println!("cleaned {}", session.id);
        }
        Ok(())
    }

    /// Clean the selected entire session. The existing change/commit refusal
    /// remains active unless `--force` was explicitly supplied.
    pub fn clean_from_repository(&self, input: &Path, force: bool) -> Result<()> {
        let Some((session, _)) = self.select_repository_worktree(input, "clean", None)? else {
            return Ok(());
        };
        print!(
            "Clean session {} and remove all {} repository worktrees{}? [y/N]: ",
            session.id,
            session.repos.len(),
            if force { " with --force" } else { "" }
        );
        io::stdout().flush()?;
        let mut confirmed = String::new();
        io::stdin().read_line(&mut confirmed)?;
        if !matches!(confirmed.trim(), "y" | "Y" | "yes" | "YES") {
            println!("clean cancelled.");
            return Ok(());
        }
        self.clean(Some(&session.id), force)
    }

    pub fn expire(&self) -> Result<()> {
        for session in self.list_sessions()? {
            if session.state == SessionState::Running && session.expired() {
                println!("TTL expired: {}", session.id);
                self.stop(&session.id)?;
            }
        }
        Ok(())
    }

    fn require_running(&self, session: &Session) -> Result<()> {
        if session.state != SessionState::Running {
            bail!(
                "session {} is {:?}; use `jbox resume {}` to restart its retained workspace",
                session.id,
                session.state,
                session.id
            );
        }
        if !self.engine.is_running(&session.container_name)? {
            bail!(
                "runtime container for {} is no longer running; worktrees were retained safely",
                session.id
            );
        }
        Ok(())
    }
    fn touch(&self, session: &mut Session) -> Result<()> {
        session.last_activity_at = Utc::now();
        self.state.save(session)
    }

    /// A container can exit outside jbox, for example after a Docker daemon
    /// restart. Reconcile that stale persisted state before exposing a session
    /// to a command so status is truthful and the retained worktree can be
    /// resumed normally.
    fn reconcile_runtime_state(&self, session: &mut Session) -> Result<()> {
        if session.state != SessionState::Running
            || self.engine.is_running(&session.container_name)?
        {
            return Ok(());
        }
        for repo in &session.repos {
            self.git.restore_and_import_guest_metadata(repo)?;
        }
        self.paths.stop_session_ssh_agent(session.ssh_agent_pid);
        self.paths.untrust_session_host(&session.known_hosts_tag)?;
        session.state = SessionState::Stopped;
        self.state.save(session)?;
        println!(
            "jbox session {} runtime was no longer running. Marked Stopped; worktrees were retained. Run `jbox resume {}` to restart it.",
            session.id, session.id
        );
        Ok(())
    }

    fn load_session(&self, id: &str) -> Result<Session> {
        let mut session = self.state.load(id)?;
        self.reconcile_runtime_state(&mut session)?;
        Ok(session)
    }

    fn list_sessions(&self) -> Result<Vec<Session>> {
        self.state
            .list()?
            .into_iter()
            .map(|mut session| {
                self.reconcile_runtime_state(&mut session)?;
                Ok(session)
            })
            .collect()
    }

    fn cleanup_worktrees(&self, repos: &[RepoState]) {
        for repo in repos {
            let _ = self.git.restore_guest_metadata(repo);
            let _ = self
                .git
                .remove_worktree(&repo.source, &repo.worktree, false);
        }
    }

    fn restore_retained_metadata(&self, repos: &[RepoState]) {
        for repo in repos {
            let _ = self.git.restore_guest_metadata(repo);
        }
    }

    /// Shared repository-scoped selector for lifecycle operations. A single
    /// matching worktree is selected directly. Multiple matches retain the
    /// selection UI, so an omitted session never chooses arbitrarily.
    /// Session lifecycle operations remain session-wide and add their own
    /// confirmation.
    fn select_repository_worktree(
        &self,
        input: &Path,
        action: &str,
        required_state: Option<SessionState>,
    ) -> Result<Option<(Session, RepoState)>> {
        let repository = Config::repository_root(input)?;
        let candidates = self
            .sessions_for_repository(&repository)?
            .into_iter()
            .filter(|(session, _)| {
                required_state
                    .as_ref()
                    .is_none_or(|state| session.state == *state)
            })
            .collect::<Vec<_>>();
        if candidates.is_empty() {
            let qualifier = match required_state {
                Some(SessionState::Running) => "running ",
                Some(SessionState::Stopped) => "stopped ",
                None => "",
            };
            bail!(
                "no {qualifier}retained jbox worktrees belong to {}",
                repository.display()
            );
        }
        if let [candidate] = candidates.as_slice() {
            let (session, repo) = candidate;
            println!(
                "Using the only matching jbox worktree for {}: {}  {:?}  {}",
                repository.display(),
                session.id,
                session.state,
                repo.branch
            );
            return Ok(Some(candidate.clone()));
        }
        if !io::stdin().is_terminal() || !io::stdout().is_terminal() {
            bail!(
                "multiple matching jbox worktrees need an interactive terminal; pass an explicit session ID instead"
            );
        }
        println!("Jbox worktrees for {}:", repository.display());
        for (index, (session, repo)) in candidates.iter().enumerate() {
            let change = self.change_label(repo);
            println!(
                "  {}) {}  {:?}  {}  [{}]",
                index + 1,
                session.id,
                session.state,
                repo.branch,
                change
            );
        }
        print!("Select a worktree to {action} (blank cancels): ");
        io::stdout().flush()?;
        let mut selected = String::new();
        io::stdin().read_line(&mut selected)?;
        let selected = selected.trim();
        if selected.is_empty() {
            println!("{action} cancelled.");
            return Ok(None);
        }
        let index: usize = selected
            .parse()
            .context("select a worktree by its displayed number")?;
        if index == 0 || index > candidates.len() {
            bail!("selection must be between 1 and {}", candidates.len());
        }
        Ok(Some(candidates[index - 1].clone()))
    }

    /// A paused host merge has one `MERGE_HEAD`: only sessions whose branch
    /// contains that commit are relevant. Keeping unrelated worktrees out of
    /// this selector makes the recovery action unambiguous in multi-session
    /// repositories.
    fn select_paused_acceptance_worktree(
        &self,
        input: &Path,
        action: &str,
    ) -> Result<Option<(Session, RepoState)>> {
        let repository = Config::repository_root(input)?;
        let Some(merge_head) = self.git.host_merge_head(&repository)? else {
            bail!(
                "no acceptance merge is paused in {}; run `jbox accept --merge` to begin one",
                repository.display()
            );
        };
        let mut candidates = Vec::new();
        for (session, repo) in self.sessions_for_repository(&repository)? {
            if self.git.branch_contains_commit(&repo, &merge_head)? {
                candidates.push((session, repo));
            }
        }
        if candidates.is_empty() {
            bail!(
                "host merge in {} is paused at {} but no retained jbox session branch contains that commit; use `git status` and `git merge --abort` or finish the host merge manually",
                repository.display(),
                merge_head
            );
        }
        if let [candidate] = candidates.as_slice() {
            let (session, repo) = candidate;
            println!(
                "Using the only session matching the paused acceptance in {}: {}  {:?}  {}",
                repository.display(),
                session.id,
                session.state,
                repo.branch
            );
            return Ok(Some(candidate.clone()));
        }
        if !io::stdin().is_terminal() || !io::stdout().is_terminal() {
            bail!(
                "`jbox accept --{action}` found {} matching sessions and needs an interactive terminal",
                candidates.len()
            );
        }
        println!(
            "Paused jbox acceptance for {} at {}:",
            repository.display(),
            &merge_head[..merge_head.len().min(12)]
        );
        for (index, (session, repo)) in candidates.iter().enumerate() {
            println!(
                "  {}) {}  {:?}  {}",
                index + 1,
                session.id,
                session.state,
                repo.branch
            );
        }
        print!("Select the originating session to {action} (blank cancels): ");
        io::stdout().flush()?;
        let mut selected = String::new();
        io::stdin().read_line(&mut selected)?;
        let selected = selected.trim();
        if selected.is_empty() {
            println!("{action} acceptance cancelled. The host merge remains paused.");
            return Ok(None);
        }
        let index: usize = selected
            .parse()
            .context("select a session by its displayed number")?;
        if index == 0 || index > candidates.len() {
            bail!("selection must be between 1 and {}", candidates.len());
        }
        Ok(Some(candidates[index - 1].clone()))
    }

    fn clear_stale_runtime_sockets(&self, ssh: &Path) -> Result<()> {
        let runtime = ssh
            .parent()
            .context("session SSH directory lacks a parent")?
            .join("runtime/jcode");
        for name in ["jbox.sock", "jbox-debug.sock", "jbox.sock.hash"] {
            let path = runtime.join(name);
            if path.exists() {
                std::fs::remove_file(&path).with_context(|| {
                    format!(
                        "could not clear stale Jcode runtime file {}",
                        path.display()
                    )
                })?;
            }
        }
        Ok(())
    }

    fn status_repository_worktree(
        &self,
        session: &Session,
        repo: &RepoState,
        diff: bool,
    ) -> Result<()> {
        let output = if diff {
            self.git.diff_stat(repo)?
        } else {
            self.git.status(repo)?
        };
        println!(
            "\n{} ({:?})\n{} [{}]",
            session.id, session.state, repo.name, repo.branch
        );
        print!("{output}");
        Ok(())
    }

    fn change_label(&self, repo: &RepoState) -> &'static str {
        match self.git.change_state(repo) {
            Ok(git::WorktreeChangeState::Clean) => "clean",
            Ok(git::WorktreeChangeState::Accepted) => "accepted",
            Ok(git::WorktreeChangeState::Changes) => "changes",
            Err(_) => "unavailable",
        }
    }

    fn validate_resume_config(
        &self,
        session: &Session,
        config: &Config,
        primary: &Path,
    ) -> Result<()> {
        let mut expected = vec![ResolvedRepository {
            source: primary.to_path_buf(),
            mount: config.workspace.mount.clone(),
            name: config.project_name(primary),
        }];
        expected.extend(config.resolve_repositories(primary)?);
        config.validate_repositories(&expected)?;
        let matches = expected.len() == session.repos.len()
            && expected
                .iter()
                .zip(&session.repos)
                .all(|(expected, actual)| {
                    expected.source == actual.source
                        && expected.mount == actual.mount
                        && expected.name == actual.name
                });
        if !matches {
            bail!(
                "cannot resume {}: .jbox.toml repository paths or mounts changed since this session was created; inspect and accept/clean the retained worktrees, then create a new session",
                session.id
            );
        }
        Ok(())
    }

    fn next_ssh_host(&self, session_id: &str) -> Result<String> {
        let used = self
            .state
            .list()?
            .into_iter()
            .map(|session| session.ssh_host)
            .collect::<std::collections::HashSet<_>>();
        let start = (session_id.bytes().fold(0u8, u8::wrapping_add) % 253) + 2;
        for offset in 0..253u8 {
            let octet = 2 + ((start - 2 + offset) % 253);
            let candidate = format!("127.0.0.{octet}");
            if !used.contains(&candidate) {
                return Ok(candidate);
            }
        }
        bail!("all dedicated jbox loopback addresses are in use")
    }
}

fn valid_apt_package(package: &str) -> bool {
    package
        .bytes()
        .next()
        .is_some_and(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
        && package
            .bytes()
            .last()
            .is_some_and(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
        && package.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'+' | b'.' | b'-')
        })
}

fn jcode_attach_args(ssh_host: &str, remote_working_dir: &str) -> Vec<String> {
    vec![
        "--ssh".into(),
        format!("jbox@{ssh_host}"),
        "--ssh-binary".into(),
        "/usr/local/bin/jcode".into(),
        "--ssh-server-socket".into(),
        JCODE_SOCKET.into(),
        "--remote-working-dir".into(),
        remote_working_dir.into(),
    ]
}

/// Make an isolated guest unmistakable before its Jcode TUI takes over the
/// terminal. Jcode's supported SSH CLI deliberately has no TUI-theme or
/// header-decoration flag, so jbox owns only terminal chrome outside the TUI.
/// The OSC title remains visible in terminal tabs, multiplexers, and desktop
/// window lists for the duration of the attached client.
fn render_jbox_session_chrome(session_id: &str, mount: &str) -> Result<()> {
    if !io::stdout().is_terminal() {
        return Ok(());
    }
    let session_id = terminal_label(session_id);
    let mount = terminal_label(mount);
    let title = jbox_terminal_title(&session_id, &mount);
    let width = 68;
    let line = "─".repeat(width - 2);
    let mut stdout = io::stdout().lock();
    writeln!(stdout, "\n┌{line}┐")?;
    writeln!(stdout, "│  📦 JBOX GUEST  {session_id}")?;
    writeln!(stdout, "│  Kata-isolated workspace: {mount}")?;
    writeln!(stdout, "└{line}┘")?;
    // BEL terminates OSC 2 across common terminals and tmux/screen pass it
    // through. Labels are strictly sanitized before interpolation.
    write!(stdout, "\x1b]2;{title}\x07")?;
    stdout.flush()?;
    Ok(())
}

/// Session IDs are generated by jbox and guest paths are configuration-
/// validated, but sanitize defensively because OSC payloads must never accept
/// terminal-control characters from persisted state.
fn terminal_label(value: &str) -> String {
    let label = value
        .chars()
        .filter(|character| !character.is_control())
        .take(80)
        .collect::<String>();
    if label.is_empty() {
        "jbox-session".into()
    } else {
        label
    }
}

fn jbox_terminal_title(session_id: &str, mount: &str) -> String {
    format!("[📦 JBOX] {session_id} · {mount}")
}

fn guest_jcode_config(jcode: &config::Jcode) -> String {
    let mut lines =
        vec!["# Generated for this jbox session. Do not store credentials here.".into()];
    lines.push("[provider]".into());
    for (key, value) in [
        ("default_provider", jcode.default_provider.as_deref()),
        ("default_model", jcode.default_model.as_deref()),
        (
            "openai_reasoning_effort",
            jcode.openai_reasoning_effort.as_deref(),
        ),
        ("openai_service_tier", jcode.openai_service_tier.as_deref()),
    ] {
        if let Some(value) = value {
            lines.push(format!("{key} = {}", toml::Value::String(value.into())));
        }
    }
    format!("{}\n", lines.join("\n"))
}

fn init_dockerfile(tools: &[String]) -> String {
    let mut dockerfile = String::from(
        "ARG JBOX_BASE_IMAGE\nFROM ${JBOX_BASE_IMAGE}\n\n# This image extends jbox's Debian-based jcode runtime.\n",
    );
    if tools.is_empty() {
        dockerfile.push_str(
            "# Add tools with a command such as:\n# RUN apt-get update && apt-get install -y --no-install-recommends ripgrep jq && rm -rf /var/lib/apt/lists/*\n",
        );
    } else {
        dockerfile.push_str(
            "RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n",
        );
        for tool in tools {
            dockerfile.push_str(&format!("    {tool} \\\n"));
        }
        dockerfile.push_str("    && rm -rf /var/lib/apt/lists/*\n");
    }
    dockerfile
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn test_app(root: &Path) -> App {
        let data = root.join("jbox-data");
        let paths = JboxPaths {
            cache: root.join("jbox-cache"),
            sessions: data.join("sessions"),
            credentials: data.join("credentials"),
            data,
        };
        App {
            state: StateStore::new(paths.clone()),
            paths,
            git: Git,
            engine: DockerEngine,
        }
    }

    fn test_session(id: &str, source: PathBuf) -> Session {
        let now = Utc::now();
        Session {
            version: 1,
            id: id.into(),
            state: SessionState::Stopped,
            container_name: format!("jbox-{id}"),
            ssh_host: "127.0.0.2".into(),
            ssh_port: 22,
            ssh_agent_pid: 0,
            known_hosts_tag: format!("# jbox:{id}"),
            created_at: now,
            last_activity_at: now,
            ttl_seconds: 86_400,
            config_path: source.join(".jbox.toml"),
            image: "test".into(),
            repos: vec![RepoState {
                name: "repo".into(),
                worktree: source.join("worktree"),
                mount: "/workspace/repo".into(),
                branch: format!("jbox/{id}/repo"),
                base_commit: "deadbeef".into(),
                host_gitfile: source.join("host-gitfile"),
                beads_snapshot: None,
                beads_bootstrap: Vec::new(),
                source,
            }],
            jcode_default_provider: None,
            jcode_default_model: None,
        }
    }

    #[test]
    fn repository_accept_lists_only_sessions_for_the_current_repository() {
        let temp = tempdir().unwrap();
        let app = test_app(temp.path());
        let current = temp.path().join("current");
        let other = temp.path().join("other");
        app.state
            .save(&test_session("current-session", current.clone()))
            .unwrap();
        app.state
            .save(&test_session("other-session", other))
            .unwrap();

        let candidates = app.sessions_for_repository(&current).unwrap();
        assert_eq!(candidates.len(), 1);
        assert_eq!(candidates[0].0.id, "current-session");
    }

    #[test]
    fn init_creates_a_config_and_tooling_image_without_overwriting() {
        let temp = tempdir().unwrap();
        assert!(
            Command::new("git")
                .args(["init", temp.path().to_str().unwrap()])
                .status()
                .unwrap()
                .success()
        );
        let app = test_app(temp.path());
        app.init(temp.path(), &["ripgrep".into(), "jq".into()])
            .unwrap();

        assert!(temp.path().join(".jbox.toml").is_file());
        assert!(Config::load(temp.path()).is_ok());
        let dockerfile = std::fs::read_to_string(temp.path().join(".jbox/Dockerfile")).unwrap();
        assert!(dockerfile.contains("FROM ${JBOX_BASE_IMAGE}"));
        assert!(dockerfile.contains("    ripgrep \\"));
        assert!(dockerfile.contains("    jq \\"));
        assert!(app.init(temp.path(), &[]).is_err());
    }

    #[test]
    fn init_rejects_unsafe_package_names_before_writing_files() {
        let temp = tempdir().unwrap();
        assert!(
            Command::new("git")
                .args(["init", temp.path().to_str().unwrap()])
                .status()
                .unwrap()
                .success()
        );
        let app = test_app(temp.path());
        assert!(app.init(temp.path(), &["jq;whoami".into()]).is_err());
        assert!(!temp.path().join(".jbox.toml").exists());
        assert!(!temp.path().join(".jbox/Dockerfile").exists());
    }

    #[test]
    fn init_uses_an_existing_dockerfile_without_replacing_it() {
        let temp = tempdir().unwrap();
        assert!(
            Command::new("git")
                .args(["init", temp.path().to_str().unwrap()])
                .status()
                .unwrap()
                .success()
        );
        let dockerfile = temp.path().join(".jbox/Dockerfile");
        std::fs::create_dir_all(dockerfile.parent().unwrap()).unwrap();
        std::fs::write(&dockerfile, "FROM debian:bookworm-slim\n").unwrap();

        test_app(temp.path()).init(temp.path(), &[]).unwrap();
        assert_eq!(
            std::fs::read_to_string(dockerfile).unwrap(),
            "FROM debian:bookworm-slim\n"
        );
    }

    #[test]
    fn skills_repository_becomes_an_isolated_guest_mount() {
        let temp = tempdir().unwrap();
        assert!(
            Command::new("git")
                .args(["init", temp.path().to_str().unwrap()])
                .status()
                .unwrap()
                .success()
        );
        std::fs::write(
            temp.path().join(".jbox.toml"),
            "version = 1\n[git]\ncredentials = 'github-cli'\n[[jcode.skills]]\nrepository = 'example/skills'\n[[jcode.skills]]\nrepository = 'K-Dense-AI/scientific-agent-skills'\nskill = 'scanpy'\n",
        )
        .unwrap();
        let (config, _) = Config::load(temp.path()).unwrap();
        let ssh = temp.path().join("session/ssh");
        std::fs::create_dir_all(&ssh).unwrap();
        let spec = test_app(temp.path())
            .container_spec(
                &config,
                &[],
                "jbox-test",
                &ssh,
                SessionLaunch {
                    image: "test-image".into(),
                    ssh_host: "127.0.0.2".into(),
                    reuse_runtime_state: false,
                },
            )
            .unwrap();

        assert!(
            spec.mounts
                .iter()
                .any(|(_, target, _)| { target == Path::new("/home/jbox/.agents/skills") })
        );
        assert!(
            spec.environment
                .contains(&("JBOX_SKILL_COUNT".into(), "2".into(),))
        );
        assert!(
            spec.environment
                .contains(&("JBOX_SKILL_0_REPOSITORY".into(), "example/skills".into(),))
        );
        assert!(
            spec.environment
                .contains(&("JBOX_SKILL_1_NAME".into(), "scanpy".into(),))
        );

        let resumed = test_app(temp.path())
            .container_spec(
                &config,
                &[],
                "jbox-test",
                &ssh,
                SessionLaunch {
                    image: "test-image".into(),
                    ssh_host: "127.0.0.2".into(),
                    reuse_runtime_state: true,
                },
            )
            .unwrap();
        assert!(
            resumed
                .environment
                .contains(&("JBOX_SKILL_COUNT".into(), "0".into(),))
        );
        assert!(
            !resumed
                .environment
                .iter()
                .any(|(name, _)| name.starts_with("JBOX_SKILL_0_"))
        );
    }

    #[test]
    fn attach_arguments_do_not_override_remote_server_configuration() {
        assert_eq!(
            jcode_attach_args("127.0.0.2", "/workspace/project"),
            vec![
                "--ssh",
                "jbox@127.0.0.2",
                "--ssh-binary",
                "/usr/local/bin/jcode",
                "--ssh-server-socket",
                JCODE_SOCKET,
                "--remote-working-dir",
                "/workspace/project",
            ]
        );
    }

    #[test]
    fn attach_arguments_never_supply_local_selection_overrides() {
        let args = jcode_attach_args("127.0.0.2", "/workspace/project");

        assert!(!args.iter().any(|arg| arg == "--provider"));
        assert!(!args.iter().any(|arg| arg == "--model"));
    }

    #[test]
    fn jbox_terminal_identity_is_distinct_and_control_safe() {
        let session = terminal_label("calm-fox\u{1b}]2;not-a-title\u{7}");
        let mount = terminal_label("/workspace/project\nnext");

        assert_eq!(session, "calm-fox]2;not-a-title");
        assert_eq!(mount, "/workspace/projectnext");
        assert_eq!(
            jbox_terminal_title(&session, &mount),
            "[📦 JBOX] calm-fox]2;not-a-title · /workspace/projectnext"
        );
    }

    #[test]
    fn guest_jcode_config_applies_project_preference_overrides() {
        let config = config::Jcode {
            persistent_credentials: true,
            skills: Vec::new(),
            agent: config::Agent::default(),
            default_provider: Some("openai".into()),
            default_model: Some("gpt-5.6-terra".into()),
            openai_reasoning_effort: Some("high".into()),
            openai_service_tier: Some("off".into()),
        };

        let rendered = guest_jcode_config(&config);
        let parsed: toml::Value = toml::from_str(&rendered).unwrap();
        assert_eq!(
            parsed["provider"]["default_model"].as_str(),
            Some("gpt-5.6-terra")
        );
        assert_eq!(
            parsed["provider"]["openai_reasoning_effort"].as_str(),
            Some("high")
        );
        assert_eq!(
            parsed["provider"]["openai_service_tier"].as_str(),
            Some("off")
        );
    }
}
